Trap errors on beta hooks
sdkman/sdkman-hooks pull request #56
Opened 2022-03-31 19:11 UTC by marc0der

This will prevent further execution of install/selfupdate if any error occurs.

2022-03-31 19:55 UTC, helpermethod commented
Left a few comments, nothing fancy.

2022-03-31 19:58 UTC, marc0der commented
@helpermethod I'm not seeing the comments. Did you submit the review?

2022-03-31 20:24 UTC, helpermethod requested changes

2022-03-31 21:23 UTC, marc0der commented on app/views/includes/trap_errors.scala.txt
> +trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
AFAIK, these scripts are both run with bash so it should work.

2022-03-31 21:27 UTC, helpermethod commented
Comments should be visible now.

2022-04-01 05:54 UTC, helpermethod approved these changes

2022-04-01 06:28 UTC, merged